"""Application service: orchestrates the end-to-end advice workflow.

This is the use-case layer. It depends only on domain ports (interfaces),
not on concrete adapters, and coordinates:

1. Deterministic quantitative analysis (:class:`PortfolioAnalyzer`).
2. Market-data retrieval via :class:`IMarketDataProvider` (OpenBB).
3. Knowledge retrieval via :class:`IKnowledgeRepository` (RAG).
4. Narrative generation via :class:`ILLMClient` (DeepSeek V3).

External calls are concurrent and fault-tolerant: if market data or the LLM
is unavailable, the service still returns a complete, deterministic plan.
"""
from __future__ import annotations

import asyncio
import datetime as dt
import json

from app.core.config import Settings
from app.core.exceptions import AdviceGenerationError, LLMError
from app.core.logging import get_logger, request_id_ctx
from app.domain.entities import KnowledgeSnippet, MarketSnapshot
from app.domain.interfaces.knowledge import IKnowledgeRepository
from app.domain.interfaces.llm import ILLMClient
from app.domain.interfaces.market_data import IMarketDataProvider
from app.schemas.request import AdviceRequest
from app.schemas.response import (
    AdviceResponse,
    DiversificationAdvice,
    KnowledgeReference,
)
from app.services.portfolio_analyzer import PortfolioAnalyzer
from app.services.prompt_builder import PromptBuilder

logger = get_logger(__name__)

_DISCLAIMERS = [
    "This output is educational information generated by an automated system, "
    "not personalized financial, tax, or legal advice.",
    "Investments carry risk, including possible loss of principal. Past "
    "performance does not guarantee future results.",
    "Consult a licensed financial advisor before acting.",
]


class AdvisorService:
    def __init__(
        self,
        *,
        settings: Settings,
        analyzer: PortfolioAnalyzer,
        prompt_builder: PromptBuilder,
        market_data: IMarketDataProvider,
        knowledge: IKnowledgeRepository,
        llm: ILLMClient,
    ) -> None:
        self._settings = settings
        self._analyzer = analyzer
        self._prompt_builder = prompt_builder
        self._market_data = market_data
        self._knowledge = knowledge
        self._llm = llm

    async def advise(self, request: AdviceRequest) -> AdviceResponse:
        try:
            return await self._advise(request)
        except Exception as exc:  # noqa: BLE001 - convert to domain error
            logger.exception("Advice generation failed")
            raise AdviceGenerationError() from exc

    async def _advise(self, request: AdviceRequest) -> AdviceResponse:
        # 1. Deterministic analysis (fast, pure).
        risk = self._analyzer.compute_risk_score(request)
        analysis = self._analyzer.analyze_portfolio(request)
        allocation = self._analyzer.target_allocation(request)
        sip = self._analyzer.sip_recommendation(request, allocation)
        emergency = self._analyzer.emergency_fund(request)
        diversification = self._analyzer.diversification(request, analysis)

        # 2 + 3. Concurrent external retrieval (market data + RAG).
        symbols = self._symbols_for(request)
        query = self._prompt_builder.build_query(request)
        market, knowledge = await asyncio.gather(
            self._market_data.get_snapshot(symbols),
            self._knowledge.retrieve(query, top_k=self._settings.rag_top_k),
        )

        # 4. Narrative from DeepSeek V3 (with deterministic fallback).
        explanation, extra_recs, llm_used, model = await self._generate_narrative(
            request=request,
            risk=risk,
            analysis=analysis,
            allocation=allocation,
            sip=sip,
            emergency=emergency,
            diversification=diversification,
            market=market,
            knowledge=knowledge,
        )
        if extra_recs:
            merged = list(dict.fromkeys([*diversification.recommendations, *extra_recs]))
            diversification = DiversificationAdvice(
                diversification_score=diversification.diversification_score,
                issues=diversification.issues,
                recommendations=merged,
            )

        return AdviceResponse(
            request_id=request_id_ctx.get(),
            generated_at=dt.datetime.now(dt.timezone.utc),
            llm_model=model,
            llm_used=llm_used,
            market_data_source=market.source,
            portfolio_analysis=analysis,
            risk_score=risk,
            asset_allocation=allocation,
            sip_recommendation=sip,
            emergency_fund=emergency,
            diversification=diversification,
            explanation=explanation,
            sources=[
                KnowledgeReference(id=k.id, title=k.title, source=k.source, score=k.score)
                for k in knowledge
            ],
            disclaimers=_DISCLAIMERS,
        )

    def _symbols_for(self, request: AdviceRequest) -> list[str]:
        held = [h.symbol for h in request.current_portfolio]
        return list(dict.fromkeys([*held, *self._settings.market_benchmark_symbols]))

    async def _generate_narrative(
        self,
        **ctx: object,
    ) -> tuple[str, list[str], bool, str]:
        request: AdviceRequest = ctx["request"]  # type: ignore[assignment]
        model = self._settings.deepseek_model
        if not self._settings.llm_enabled:
            logger.info("LLM disabled; using deterministic explanation")
            return self._fallback_explanation(**ctx), [], False, "deterministic-fallback"

        messages = self._prompt_builder.build_messages(**ctx)  # type: ignore[arg-type]
        try:
            result = await self._llm.complete(messages, json_mode=True)
        except LLMError:
            logger.warning("DeepSeek unavailable; using deterministic explanation")
            return self._fallback_explanation(**ctx), [], False, "deterministic-fallback"

        explanation, extra_recs = self._parse_llm_json(result.content)
        if not explanation:
            return self._fallback_explanation(**ctx), extra_recs, False, "deterministic-fallback"
        return explanation, extra_recs, True, result.model

    @staticmethod
    def _parse_llm_json(content: str) -> tuple[str, list[str]]:
        text = content.strip()
        if text.startswith("```"):
            text = text.strip("`")
            text = text[text.find("{") : text.rfind("}") + 1]
        try:
            data = json.loads(text)
        except (ValueError, TypeError):
            # Not valid JSON: treat the whole thing as the explanation.
            return content.strip(), []
        explanation = str(data.get("explanation", "")).strip()
        recs = data.get("diversification_recommendations", []) or []
        recs = [str(r).strip() for r in recs if str(r).strip()]
        return explanation, recs

    def _fallback_explanation(self, **ctx: object) -> str:
        request: AdviceRequest = ctx["request"]  # type: ignore[assignment]
        risk = ctx["risk"]
        emergency = ctx["emergency"]
        sip = ctx["sip"]
        allocation = ctx["allocation"]
        equity = next(
            (i.target_pct for i in allocation.target if i.asset_class.value == "equity"),  # type: ignore[attr-defined]
            0.0,
        )
        return (
            f"Based on a {request.risk_profile.tolerance.value} risk profile and a "
            f"{request.risk_profile.investment_horizon_years}-year horizon, the plan targets "
            f"a risk score of {risk.score}/100 ({risk.band.value}) with roughly "  # type: ignore[attr-defined]
            f"{equity:.0f}% in equities balanced by fixed income, cash and real assets. "
            f"Prioritise an emergency fund of {emergency.recommended_amount:,.0f} "  # type: ignore[attr-defined]
            f"({emergency.months_of_expenses:.0f} months of expenses) before scaling risk assets. "  # type: ignore[attr-defined]
            f"Deploy about {sip.recommended_monthly_amount:,.0f} per month through SIPs to "  # type: ignore[attr-defined]
            "benefit from rupee-cost averaging, and rebalance to target at least annually. "
            "This is educational information, not personalized financial advice."
        )
